POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRlaWphIiwiaWQiOiI2M2RiYWQyMTkxMzQxZGM1MTcwY2FhMjMiLCJpYXQiOjE2NzU0NTk0MjR9.k1cLQoUvJvWOVvWdhMKwkzY7kOW6x3zjXKNlTxV6ZN8

{
    "title": "Huuli",
    "author": "Teija",
    "url": "www.testi.com",
    "likes": 22,
    "userId": "63dbad2191341dc5170caa23"
}